#!/bin/sh
#PBS-lwalltime=72:00:00
#PBS-lselect=1:ncpus=8:mpiprocs=8:ompthreads=1:mem=23500mb
module load netcdf
ulimit -s unlimited
cd /scratch/cdenamie/HYCOM/HYCOM2ROMS
exec ./smooth_temp > submit_temp.out
